wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.48.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737889524.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 95
      - 100
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 95
      - 100
      3:
      - 2
      - 13
      - 23
      - 62
      4: 3.10.16
      5: 0.16.5
      6: 4.48.0
      8:
      - 5
      13: linux-x86_64
task_configs:
  desc: null
  value:
    mmbench_en_dev_lite:
      task: mmbench_en_dev_lite
      dataset_path: lmms-lab/LMMs-Eval-Lite
      dataset_name: mmbench_en_dev
      dataset_kwargs:
        token: true
      test_split: lite
      full_docs: false
      process_results_use_image: false
      doc_to_visual: <function mmbench_doc_to_visual at 0x7fff09957b50>
      doc_to_text: <function mmbench_doc_to_text at 0x7fff09990dc0>
      doc_to_target: answer
      process_results: <function mmbench_process_results at 0x7fff099912d0>
      description: ''
      target_delimiter: ' '
      fewshot_delimiter: '


        '
      num_fewshot: 0
      metric_list:
      - metric: gpt_eval_score
        aggregation: en_utils.mmbench_aggregate_dev_results_eval
        higher_is_better: true
      - metric: submission
        aggregation: en_utils.mmbench_aggregate_dev_results_submission
        higher_is_better: true
      output_type: generate_until
      generation_kwargs:
        until:
        - 'ASSISTANT:'
        max_new_tokens: 1024
        temperature: 0.0
        top_p: 1.0
        num_beams: 1
        do_sample: false
      repeats: 1
      should_decontaminate: false
      lmms_eval_specific_kwargs:
        default:
          pre_prompt: ''
          post_prompt: '

            Answer with the option''s letter from the given choices directly.'
        pre_prompt: ''
        post_prompt: '

          Answer with the option''s letter from the given choices directly.'
      model_specific_generation_kwargs:
        llava:
          image_aspect_ratio: original
cli_configs:
  desc: null
  value:
    model: llava_onevision
    model_args: pretrained=lmms-lab/llava-onevision-qwen2-0.5b-ov
    batch_size: '1'
    batch_sizes: []
    device: null
    use_cache: null
    limit: null
    bootstrap_iters: 100000
    gen_kwargs: ''
    random_seed: 0
    numpy_seed: 1234
    torch_seed: 1234
    fewshot_seed: 1234
