
python3 -m accelerate.commands.launch \
    --num_processes=1 \
    --main_process_port 29832 \
    -m lmms_eval \
    --model llava \
    --model_args pretrained="Yi-VL-6B" \
    --tasks mmstar,mmbench_en_dev_lite,vqav2_val_lite \
    --batch_size 1 \
    --log_samples \
    --log_samples_suffix llava_v1.6_pope \
    --output_path ./logs/ \
    --generation_type recursion \
    --fix_grid 2x2 \
    --attention_thresholding_type attn_topk \
    --attention_threshold "2.5" \
    --positional_embedding_type bilinear_interpolation \
    --remove_unpadding True \
    --attn_norm None \
    --stages "0" \
    --verbosity DEBUG \
    --square 1 \
    --contrastive_alphas "1.0" \
    --use_noised_for_contrastive True \
    --wandb_args "project=llava1.6_recursive_eval_vcd,entity=VLM_Hallucination_Woohyeon,name=yi-vl-6b-1.0-0.2" \
