wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.48.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737830557.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 95
      - 100
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 95
      - 100
      3:
      - 2
      - 13
      - 23
      - 62
      4: 3.10.16
      5: 0.16.5
      6: 4.48.0
      8:
      - 5
      13: linux-x86_64
task_configs:
  desc: null
  value:
    mmstar:
      task: mmstar
      dataset_path: Lin-Chen/MMStar
      dataset_kwargs:
        token: true
      test_split: val
      full_docs: false
      process_results_use_image: false
      doc_to_visual: <function mmstar_doc_to_visual at 0x7fff0995bac0>
      doc_to_text: <function mmstar_doc_to_text at 0x7fff0995bf40>
      doc_to_target: answer
      process_results: <function mmstar_process_results at 0x7fff09994430>
      description: ''
      target_delimiter: ' '
      fewshot_delimiter: '


        '
      num_fewshot: 0
      metric_list:
      - metric: coarse perception
        aggregation: utils.mmstar_aggregate_results
        higher_is_better: true
      - metric: fine-grained perception
        aggregation: utils.mmstar_aggregate_results
        higher_is_better: true
      - metric: instance reasoning
        aggregation: utils.mmstar_aggregate_results
        higher_is_better: true
      - metric: logical reasoning
        aggregation: utils.mmstar_aggregate_results
        higher_is_better: true
      - metric: science & technology
        aggregation: utils.mmstar_aggregate_results
        higher_is_better: true
      - metric: math
        aggregation: utils.mmstar_aggregate_results
        higher_is_better: true
      - metric: average
        aggregation: utils.mmstar_aggregate_results
        higher_is_better: true
      output_type: generate_until
      generation_kwargs:
        until:
        - '


          '
        do_sample: false
      repeats: 1
      should_decontaminate: false
      metadata:
      - version: 0.0
      lmms_eval_specific_kwargs:
        default:
          pre_prompt: ''
          post_prompt: '

            Answer with the option''s letter from the given choices directly'
        pre_prompt: ''
        post_prompt: '

          Answer with the option''s letter from the given choices directly'
cli_configs:
  desc: null
  value:
    model: llava_onevision
    model_args: pretrained=lmms-lab/llava-onevision-qwen2-0.5b-ov
    batch_size: '1'
    batch_sizes: []
    device: null
    use_cache: null
    limit: null
    bootstrap_iters: 100000
    gen_kwargs: ''
    random_seed: 0
    numpy_seed: 1234
    torch_seed: 1234
    fewshot_seed: 1234
